title: Gambars
modelClass: Yfktn\EventGubernur\Models\Gambars
list: $/yfktn/eventgubernur/models/gambars/columns.yaml
recordUrl: 'yfktn/eventgubernur/gambars/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
