name: Gambars
form: $/yfktn/eventgubernur/models/gambars/fields.yaml
modelClass: Yfktn\EventGubernur\Models\Gambars
defaultRedirect: yfktn/eventgubernur/gambars
create:
    redirect: 'yfktn/eventgubernur/gambars/update/:id'
    redirectClose: yfktn/eventgubernur/gambars
update:
    redirect: yfktn/eventgubernur/gambars
    redirectClose: yfktn/eventgubernur/gambars
