name: Agenda Kegiatan
form: $/yfktn/eventgubernur/models/egitem/item.yaml
modelClass: Yfktn\EventGubernur\Models\EGItem
defaultRedirect: yfktn/eventgubernur/jadwalgubernur
create:
    redirect: 'yfktn/eventgubernur/jadwalgubernur/update/:id'
    redirectClose: yfktn/eventgubernur/jadwalgubernur
update:
    redirect: yfktn/eventgubernur/jadwalgubernur
    redirectClose: yfktn/eventgubernur/jadwalgubernur
