name: Agenda Kegiatan
form: $/yanfriskantoni/eventgubernur/models/egitem/item.yaml
modelClass: YanFriskantoni\EventGubernur\Models\EGItem
defaultRedirect: yanfriskantoni/eventgubernur/jadwalgubernur
create:
    redirect: 'yanfriskantoni/eventgubernur/jadwalgubernur/update/:id'
    redirectClose: yanfriskantoni/eventgubernur/jadwalgubernur
update:
    redirect: yanfriskantoni/eventgubernur/jadwalgubernur
    redirectClose: yanfriskantoni/eventgubernur/jadwalgubernur
