list: $/yfktn/eventgubernur/models/egitem/columns.yaml
modelClass: Yfktn\EventGubernur\Models\EGItem
title: Agenda Kegiatan
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yfktn/eventgubernur/jadwalgubernur/update/:id'
