name: Pencetakan Jadwal
modelClass: Yfktn\EventGubernur\Models\EGItem
form: $/yfktn/eventgubernur/models/egitem/cetak.yaml
defaultRedirect: yfktn/eventgubernur/cetakjadwal/create
create:
    redirect: 'yfktn/eventgubernur/cetakjadwal/update/:id'
    redirectClose: yfktn/eventgubernur/cetakjadwal
update:
    redirect: yfktn/eventgubernur/cetakjadwal
    redirectClose: yfktn/eventgubernur/cetakjadwal
preview: {  }
